# MediaPipe Objectron vertices/landmarks rendering CPU subgraph.

type: "RendererSubgraph"

input_stream: "IMAGE:input_image"
input_stream: "MULTI_LANDMARKS:multi_landmarks"
input_stream: "NORM_RECTS:multi_rect"
output_stream: "IMAGE:output_image"


# Subgraph that converts multilandmarks to renderable data.
node {
  calculator: "RendererMultiLandmarksSubgraph"
  input_stream: "MULTI_LANDMARKS:multi_landmarks"
  output_stream: "RENDER_DATA:multi_landmarks_render_data"
}

# Converts normalized rects to drawing primitives for annotation overlay.
node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:multi_rect"
  output_stream: "RENDER_DATA:multi_rect_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: false
      color { r: 255 g: 0 b: 0 }
      thickness: 4.0
    }
  }
}

# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE:input_image"
  input_stream: "VECTOR:multi_landmarks_render_data"
  input_stream: "multi_rect_render_data"
  output_stream: "IMAGE:output_image"
}
